"""Add economy configuration fields to bot_config

Revision ID: 3d9f8a2e1b5c
Revises: 2bc8023392e7
Create Date: 2026-02-09 09:02:03.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9f8a2e1b5c'
down_revision: Union[str, None] = '2bc8023392e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # ECONOMY CONFIGURATION MIGRATION (Phase 19 - Wave 3)
    #
    # Adds configurable economy settings to BotConfig singleton:
    # - level_formula: Formula for calculating user levels
    # - besitos_per_reaction: Besitos awarded per reaction
    # - besitos_daily_gift: Besitos awarded for daily gift claim
    # - besitos_daily_streak_bonus: Bonus besitos for streak maintenance
    # - max_reactions_per_day: Daily reaction limit per user
    #
    # These values are used by WalletService, ReactionService, and StreakService.
    #
    op.add_column('bot_config', sa.Column('level_formula', sa.String(length=255), nullable=True))
    op.add_column('bot_config', sa.Column('besitos_per_reaction', sa.Integer(), nullable=True))
    op.add_column('bot_config', sa.Column('besitos_daily_gift', sa.Integer(), nullable=True))
    op.add_column('bot_config', sa.Column('besitos_daily_streak_bonus', sa.Integer(), nullable=True))
    op.add_column('bot_config', sa.Column('max_reactions_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'max_reactions_per_day')
    op.drop_column('bot_config', 'besitos_daily_streak_bonus')
    op.drop_column('bot_config', 'besitos_daily_gift')
    op.drop_column('bot_config', 'besitos_per_reaction')
    op.drop_column('bot_config', 'level_formula')
    # ### end Alembic commands ###
