"""Initial schema with all models

Revision ID: 29019dace4c7
Revises: 
Create Date: 2026-01-29 05:04:41.640597+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29019dace4c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vip_channel_id', sa.String(length=50), nullable=True),
    sa.Column('free_channel_id', sa.String(length=50), nullable=True),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True),
    sa.Column('vip_reactions', sa.JSON(), nullable=True),
    sa.Column('free_reactions', sa.JSON(), nullable=True),
    sa.Column('subscription_fees', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('social_instagram', sa.String(length=200), nullable=True),
    sa.Column('social_tiktok', sa.String(length=200), nullable=True),
    sa.Column('social_x', sa.String(length=200), nullable=True),
    sa.Column('free_channel_invite_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.Enum('FREE_CONTENT', 'VIP_CONTENT', 'VIP_PREMIUM', name='contentcategory'), nullable=False),
    sa.Column('type', sa.Enum('STANDARD', 'BUNDLE', 'COLLECTION', name='packagetype'), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_category_active', 'content_packages', ['category', 'is_active'], unique=False)
    op.create_index('idx_content_type_active', 'content_packages', ['type', 'is_active'], unique=False)
    op.create_index(op.f('ix_content_packages_is_active'), 'content_packages', ['is_active'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_role', sa.Enum('FREE', 'VIP', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('new_role', sa.Enum('FREE', 'VIP', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('ADMIN_GRANTED', 'ADMIN_REVOKED', 'VIP_PURCHASED', 'VIP_REDEEMED', 'VIP_EXPIRED', 'VIP_EXTENDED', 'VIP_ENTRY_COMPLETED', 'MANUAL_CHANGE', 'SYSTEM_AUTOMATIC', name='rolechangereason'), nullable=False),
    sa.Column('change_source', sa.String(length=50), nullable=False),
    sa.Column('change_metadata', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_log_changed_by_changed_at', 'user_role_change_log', ['changed_by', 'changed_at'], unique=False)
    op.create_index('idx_role_log_user_changed_at', 'user_role_change_log', ['user_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_user_role_change_log_changed_at'), 'user_role_change_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_user_role_change_log_changed_by'), 'user_role_change_log', ['changed_by'], unique=False)
    op.create_index(op.f('ix_user_role_change_log_user_id'), 'user_role_change_log', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('FREE', 'VIP', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('free_channel_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_date', 'free_channel_requests', ['processed', 'request_date'], unique=False)
    op.create_index('idx_user_date', 'free_channel_requests', ['user_id', 'request_date'], unique=False)
    op.create_index(op.f('ix_free_channel_requests_processed'), 'free_channel_requests', ['processed'], unique=False)
    op.create_index(op.f('ix_free_channel_requests_user_id'), 'free_channel_requests', ['user_id'], unique=False)
    op.create_table('invitation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_used_created', 'invitation_tokens', ['used', 'created_at'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_invitation_tokens_used'), 'invitation_tokens', ['used'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('is_attended', sa.Boolean(), nullable=False),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interest_user_package', 'user_interests', ['user_id', 'package_id'], unique=True)
    op.create_index('idx_interest_user_package_attended', 'user_interests', ['user_id', 'package_id', 'is_attended'], unique=False)
    op.create_index(op.f('ix_user_interests_is_attended'), 'user_interests', ['is_attended'], unique=False)
    op.create_index(op.f('ix_user_interests_package_id'), 'user_interests', ['package_id'], unique=False)
    op.create_index(op.f('ix_user_interests_user_id'), 'user_interests', ['user_id'], unique=False)
    op.create_table('vip_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vip_entry_stage', sa.Integer(), nullable=True),
    sa.Column('vip_entry_token', sa.String(length=64), nullable=True),
    sa.Column('invite_link_sent_at', sa.DateTime(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['invitation_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vip_entry_token')
    )
    op.create_index('idx_status_expiry', 'vip_subscribers', ['status', 'expiry_date'], unique=False)
    op.create_index('idx_vip_entry_stage', 'vip_subscribers', ['vip_entry_stage'], unique=False)
    op.create_index(op.f('ix_vip_subscribers_status'), 'vip_subscribers', ['status'], unique=False)
    op.create_index(op.f('ix_vip_subscribers_user_id'), 'vip_subscribers', ['user_id'], unique=True)
    op.create_index(op.f('ix_vip_subscribers_vip_entry_stage'), 'vip_subscribers', ['vip_entry_stage'], unique=False)

    # Insert default configuration with social media links
    op.execute("""
        INSERT INTO bot_config (id, wait_time_minutes, vip_reactions, free_reactions, subscription_fees, created_at, updated_at, social_instagram, social_tiktok, social_x)
        VALUES (1, 60, '["❤️", "🔥", "😍"]', '["❤️", "👍"]', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ella.es.diana', 'srtakinky', 'SrtaKinky')
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vip_subscribers_vip_entry_stage'), table_name='vip_subscribers')
    op.drop_index(op.f('ix_vip_subscribers_user_id'), table_name='vip_subscribers')
    op.drop_index(op.f('ix_vip_subscribers_status'), table_name='vip_subscribers')
    op.drop_index('idx_vip_entry_stage', table_name='vip_subscribers')
    op.drop_index('idx_status_expiry', table_name='vip_subscribers')
    op.drop_table('vip_subscribers')
    op.drop_index(op.f('ix_user_interests_user_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_package_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_is_attended'), table_name='user_interests')
    op.drop_index('idx_interest_user_package_attended', table_name='user_interests')
    op.drop_index('idx_interest_user_package', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_invitation_tokens_used'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.drop_index('idx_token_used_created', table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    op.drop_index(op.f('ix_free_channel_requests_user_id'), table_name='free_channel_requests')
    op.drop_index(op.f('ix_free_channel_requests_processed'), table_name='free_channel_requests')
    op.drop_index('idx_user_date', table_name='free_channel_requests')
    op.drop_index('idx_processed_date', table_name='free_channel_requests')
    op.drop_table('free_channel_requests')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_role_change_log_user_id'), table_name='user_role_change_log')
    op.drop_index(op.f('ix_user_role_change_log_changed_by'), table_name='user_role_change_log')
    op.drop_index(op.f('ix_user_role_change_log_changed_at'), table_name='user_role_change_log')
    op.drop_index('idx_role_log_user_changed_at', table_name='user_role_change_log')
    op.drop_index('idx_role_log_changed_by_changed_at', table_name='user_role_change_log')
    op.drop_table('user_role_change_log')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_content_packages_is_active'), table_name='content_packages')
    op.drop_index('idx_content_type_active', table_name='content_packages')
    op.drop_index('idx_content_category_active', table_name='content_packages')
    op.drop_table('content_packages')
    op.drop_table('bot_config')
    # ### end Alembic commands ###
