"""Add gamification tables: user_gamification_profiles and transactions

Revision ID: 2bc8023392e7
Revises: 29019dace4c7
Create Date: 2026-02-09 08:43:14.262725+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc8023392e7'
down_revision: Union[str, None] = '29019dace4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # ATOMIC TRANSACTION PATTERN:
    # This migration creates the foundation for an atomic economy system.
    # All besito operations must use UPDATE SET col = col + delta pattern
    # to ensure thread-safety and prevent race conditions.
    #
    # Example:
    #   UPDATE user_gamification_profiles
    #   SET balance = balance + 10, total_earned = total_earned + 10
    #   WHERE user_id = ?
    #
    # Every balance change must insert a corresponding transaction record
    # for complete audit trail.
    #
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EARN_REACTION', 'EARN_DAILY', 'EARN_STREAK', 'EARN_REWARD', 'EARN_ADMIN', 'SPEND_SHOP', 'SPEND_ADMIN', name='transactiontype'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_type_created', 'transactions', ['type', 'created_at'], unique=False)
    op.create_index('idx_transaction_user_created', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_transaction_user_type', 'transactions', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_gamification_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gamification_level_balance', 'user_gamification_profiles', ['level', 'balance'], unique=False)
    op.create_index(op.f('ix_user_gamification_profiles_level'), 'user_gamification_profiles', ['level'], unique=False)
    op.create_index(op.f('ix_user_gamification_profiles_user_id'), 'user_gamification_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gamification_profiles_user_id'), table_name='user_gamification_profiles')
    op.drop_index(op.f('ix_user_gamification_profiles_level'), table_name='user_gamification_profiles')
    op.drop_index('idx_gamification_level_balance', table_name='user_gamification_profiles')
    op.drop_table('user_gamification_profiles')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('idx_transaction_user_type', table_name='transactions')
    op.drop_index('idx_transaction_user_created', table_name='transactions')
    op.drop_index('idx_transaction_type_created', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
